name: My GitHub Actions Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build code
      run: pipeline {
    agent any
    stages {
        stage('Get project') {
            steps {
                git 'https://github.com/creativetimofficial/vue-paper-dashboard.git'
            }
        }
        stage('Install dependencies') {
            steps {
              sh 'npm install'
            }
        }
        stage('Build project') {
            steps {
               sh 'npm run build'
            }
        }
    }
}
